creating feature tests
softberg/quantum-php-project pull request #102
Opened 2024-10-31 14:18 UTC by Vahram1995

2024-10-31 14:55 UTC, Arno2005 approved these changes

2024-10-31 17:02 UTC, armanist requested changes

2024-10-31 17:02 UTC, armanist commented on tests/Feature/BaseTestCase.php
> +class BaseTestCase extends TestCase
Rename this `AppTestCase`

2024-11-01 13:59 UTC, armanist approved these changes

2024-11-01 13:59 UTC, merged