swagger + UI integration to have API tester ready to go
softberg/quantum-php-project pull request #63
Opened 2022-09-27 14:31 UTC by hatik92

2022-10-03 13:08 UTC, armanist requested changes

2022-10-03 15:45 UTC, armanist commented on modules/Api/Controllers/AuthController.php
>       * Sign in action
Only the method description needed to be moved to the top not a param definitions

2022-10-04 14:42 UTC, armanist requested changes
The doc-blcoks are still different from preferred format, it should be

1. Method description
2. @OA block
3. @params, @return, @throws block

2022-10-05 08:03 UTC, armanist requested changes

2022-10-05 08:03 UTC, armanist commented on composer.json
> +            "php qt install:openapi",
This will throw an error, because the module name is not provided

2022-10-05 15:28 UTC, armanist approved these changes

2022-10-05 15:31 UTC, Vahram1995 approved these changes

2022-10-05 15:40 UTC, merged